# apiVersion: secretsmanager.services.k8s.aws/v1alpha1
# kind: Secret
# metadata:
#   name: test-secret
#   namespace: default
# spec:
#   description: Test
#   name: workload-cluster3-test-secret
#   secretString: 
#     key: '{"message": "hello world"}'
#   tags:
#   - key: fleet_member
#     value: spoke
#   - key: tenant
#     value: tenant1
#   - key: environment
#     value: staging
#   - key: aws_cluster_name
#     value: workload-cluster3
#   - key: workloads
#     value: "true"
#   - key: argocd.argoproj.io/secret-type
#     value: cluster
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: test-secret
#   namespace: default
# type: Opaque
# stringData:
#   username: "my-username"
#   password: "my-password"
---
apiVersion: secretsmanager.services.k8s.aws/v1alpha1
kind: Secret
metadata:
  name: test-secret3
  namespace: workload-cluster3
spec:
  name: test-secret3
  description: Testing Secret
  secretString:
    key: test-secret-key
    name: test-secret3
    namespace: workload-cluster3
  #kmsKeyID: "alias/aws/secretsmanager"
  tags:
    - key: "Environment"
      value: "Production"
    - key: "Team"
      value: "DevOps"
  # replicaRegions:
  #   - kmsKeyID: "alias/aws/secretsmanager"
  #     region: "eu-west-2"
  #   - kmsKeyID: "alias/aws/secretsmanager"
  #     region: "eu-west-3"
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret3
  namespace: workload-cluster3
type: Opaque
data:
  test-secret-key: ZnVjayB5b3UK # Base64 encoded value of the secret (e.g., 'test-value')