apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: cluster3
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
    name: cluster3
    tenant: auto1
    environment: staging
    region: us-west-2
    k8sVersion: '1.31'
    accountId: '798082067117'
    managementAccountId: '382076407153'
    adminRoleName: Admin
    fleetSecretManagerSecretNameSuffix: argocd-secret-name2
    domainName: cluster3.rosa.allamand.com
    cidr: {}
    gitops:
      addonsRepoRevision: "centralized-argocd"
      fleetRepoRevision: "centralized-argocd"
      platformRepoRevision: "centralized-argocd"
      workloadRepoRevision: "centralized-argocd"
    addons: {}
