apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: cluster1
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"  
spec:
    name: cluster1
    #tenant: tenant1
    #environment: staging    
    #region: us-west-2
    k8sVersion: '1.30'
    accountId: '382076407153'
    managementAccountId: '382076407153'
    domainName: cluster1.sallaman.people.aws.dev
    #subHostedZone:
    #  create: true
    #  domainNameRef: sallaman.people.aws.dev
    cidr:
      vpcCidr: "10.0.0.0/16"
    gitops:
      addonsRepoRevision: "seb"
      fleetRepoRevision: "seb"
      platformRepoRevision: "seb"
      workloadRepoRevision: "seb"
    addons:
      external_dns_namespace: 'external-dns'
   