apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: workload-cluster3
spec:
    name: workload-cluster3
    tenant: tenant1
    environment: staging
    region: us-west-2
    k8sVersion: '1.30'
    accountId: '798082067117'
    managementAccountId: '382076407153'
    adminRoleName: Admin
    nodesCount: 6
    fleetSecretManagerSecretName: workload-cluster3-argocd-secret5
    domainName: workload-cluster3.rosa.allamand.com
    cidr:
      vpcCidr: "10.0.0.0/16"
      publicSubnet1Cidr: "10.0.1.0/24"
      publicSubnet2Cidr: "10.0.2.0/24"
      privateSubnet1Cidr: "10.0.11.0/24"
      privateSubnet2Cidr: "10.0.12.0/24"
    gitops:
        addonsRepoPath: "bootstrap"
        addonsRepoRevision: "HEAD"
        addonsRepoSecretKey: "eks-fleet-workshop-gitops-addons"
        addonsRepoUrl: "https://d1t8il14om2k8l.cloudfront.net/gitea/workshop-user/eks-fleet-workshop-gitops-addons"
        fleetRepoPath: "bootstrap"
        fleetRepoRevision: "HEAD"
        fleetRepoSecretKey: "eks-fleet-workshop-gitops-fleet"
        fleetRepoUrl: "https://d1t8il14om2k8l.cloudfront.net/gitea/workshop-user/eks-fleet-workshop-gitops-fleet"
        platformRepoBasePath: ""
        platformRepoPath: "bootstrap"
        platformRepoRevision: "HEAD"
        platformRepoSecretKey: "eks-fleet-workshop-gitops-platform"
        platformRepoUrl: "https://d1t8il14om2k8l.cloudfront.net/gitea/workshop-user/eks-fleet-workshop-gitops-platform"
        workloadRepoBasePath: ""
        workloadRepoPath: ""
        workloadRepoRevision: "HEAD"
        workloadRepoSecretKey: "eks-fleet-workshop-gitops-workloads"
        workloadRepoUrl: "https://d1t8il14om2k8l.cloudfront.net/gitea/workshop-user/eks-fleet-workshop-gitops-apps"
