apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: workload-cluster3
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
    name: workload-cluster3
    tenant: tenant1
    environment: staging
    region: us-west-2
    k8sVersion: '1.30'
    accountId: '798082067117'
    managementAccountId: '382076407153'
    adminRoleName: Admin
    nodesCount: 6
    fleetSecretManagerSecretNameSuffix: argocd-secret-name
    domainName: workload-cluster3.rosa.allamand.com
    gitops:
        addonsRepoRevision: "seb"
