apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: workload-cluster3
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
    name: workload-cluster3
    tenant: tenant1
    environment: staging
    region: us-west-2
    k8sVersion: '1.30'
    accountId: '798082067117'
    managementAccountId: '382076407153'
    adminRoleName: Admin
    nodesCount: 6
    fleetSecretManagerSecretNameSuffix: argocd-secret-name
    domainName: workload-cluster3.rosa.allamand.com
    cidr:
      vpcCidr: "10.0.0.0/16"
      publicSubnet1Cidr: "10.0.1.0/24"
      publicSubnet2Cidr: "10.0.2.0/24"
      privateSubnet1Cidr: "10.0.11.0/24"
      privateSubnet2Cidr: "10.0.12.0/24"
    gitops:
        addonsRepoRevision: "seb"
