{{- range $key, $value := .Values.clusters }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $key }}
  annotations:
    services.k8s.aws/team-id: "{{ $key }}"
    services.k8s.aws/default-region: "{{ $value.region }}"
    argocd.argoproj.io/tracking-id: "{{ $key }}:apps/Namespace:{{ $key }}/{{ $key }}"
{{- end }}
