apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: eksclusterwithvpc.kro.run
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  schema:
    apiVersion: v1alpha1
    kind: EksclusterWithVpc
    spec:
      name: string
      tenant: string | default="tenant1"
      environment: string | default="staging"
      region: string
      k8sVersion: string
      accountId: string
      managementAccountId: string
      adminRoleName: string | default="Admin"
      nodesCount: integer
      fleetSecretManagerSecretName: string
      domainName: string
      cidr:
        vpcCidr: string | default="10.0.0.0/16"
        publicSubnet1Cidr: string | default="10.0.1.0/24"
        publicSubnet2Cidr: string | default="10.0.2.0/24"
        privateSubnet1Cidr: string | default="10.0.11.0/24"
        privateSubnet2Cidr: string | default="10.0.12.0/24"
      gitops:
        addonsRepoBasePath: string | default=""
        addonsRepoPath: string | default="bootstrap"
        addonsRepoRevision: string | default="HEAD"
        addonsRepoSecretKey: string | default="eks-fleet-workshop-gitops-addons"
        addonsRepoUrl: string | default="https://d1t8il14om2k8l.cloudfront.net/gitea/workshop-user/eks-fleet-workshop-gitops-addons"
        fleetRepoBasePath: string | default=""
        fleetRepoPath: string | default="bootstrap"
        fleetRepoRevision: string | default="HEAD"
        fleetRepoSecretKey: string | default="eks-fleet-workshop-gitops-fleet"
        fleetRepoUrl: string | default="https://d1t8il14om2k8l.cloudfront.net/gitea/workshop-user/eks-fleet-workshop-gitops-fleet" 
        platformRepoBasePath: string | default=""
        platformRepoPath: string | default="bootstrap"
        platformRepoRevision: string | default="HEAD"
        platformRepoSecretKey: string | default="eks-fleet-workshop-gitops-platform"
        platformRepoUrl: string | default="https://d1t8il14om2k8l.cloudfront.net/gitea/workshop-user/eks-fleet-workshop-gitops-platform"
        workloadRepoBasePath: string | default=""
        workloadRepoPath: string | default=""
        workloadRepoRevision: string | default="HEAD"
        workloadRepoSecretKey: string | default="eks-fleet-workshop-gitops-workloads"
        workloadRepoUrl: string | default="https://d1t8il14om2k8l.cloudfront.net/gitea/workshop-user/eks-fleet-workshop-gitops-apps"

  resources:
  - id: vpc
    template:
      apiVersion: kro.run/v1alpha1
      kind: Vpc
      metadata:
        name: ${schema.spec.name}
        namespace: ${schema.spec.name}
        annotations:
          argocd.argoproj.io/tracking-id: clusters:kro.run/Vpc:${schema.spec.name}/${schema.spec.name}
      spec:
        name: ${schema.spec.name}
        region: ${schema.spec.region}
        cidr:
          vpcCidr: ${schema.spec.cidr.vpcCidr}
          publicSubnet1Cidr: ${schema.spec.cidr.publicSubnet1Cidr}
          publicSubnet2Cidr: ${schema.spec.cidr.publicSubnet2Cidr}
          privateSubnet1Cidr: ${schema.spec.cidr.privateSubnet1Cidr}
          privateSubnet2Cidr: ${schema.spec.cidr.privateSubnet2Cidr}
  - id: eks
    template:
      apiVersion: kro.run/v1alpha1
      kind: EksCluster
      metadata:
        name: ${schema.spec.name}
        namespace: ${schema.spec.name}
        annotations:
          argocd.argoproj.io/tracking-id: clusters:kro.run/EksCluster:${schema.spec.name}/${schema.spec.name}                     
      spec:
          name: ${schema.spec.name}
          tenant: ${schema.spec.tenant}
          environment: ${schema.spec.environment}
          region: ${schema.spec.region}
          accountId: ${schema.spec.accountId}
          managementAccountId: ${schema.spec.managementAccountId}
          k8sVersion: ${schema.spec.k8sVersion}
          adminRoleName: ${schema.spec.adminRoleName}
          nodesCount: ${schema.spec.nodesCount}
          fleetSecretManagerSecretName2: ${schema.spec.fleetSecretManagerSecretName}
          domainName: ${schema.spec.domainName}
          network:
            vpcID: ${vpc.status.vpcID}
            subnets:
              controlplane:
                subnet1ID: ${vpc.status.privateSubnet1ID}
                subnet2ID: ${vpc.status.privateSubnet2ID}
              workers:
                subnet1ID: ${vpc.status.privateSubnet1ID}
                subnet2ID: ${vpc.status.privateSubnet2ID}
          gitops:
            addonsRepoBasePath: ${schema.spec.gitops.addonsRepoBasePath}
            addonsRepoPath: ${schema.spec.gitops.addonsRepoPath}
            addonsRepoRevision: ${schema.spec.gitops.addonsRepoRevision}
            addonsRepoSecretKey: ${schema.spec.gitops.addonsRepoSecretKey}
            addonsRepoUrl: ${schema.spec.gitops.addonsRepoUrl}
            fleetRepoBasePath: ${schema.spec.gitops.fleetRepoBasePath}
            fleetRepoPath: ${schema.spec.gitops.fleetRepoPath}
            fleetRepoRevision: ${schema.spec.gitops.fleetRepoRevision}
            fleetRepoSecretKey: ${schema.spec.gitops.fleetRepoSecretKey}
            fleetRepoUrl: ${schema.spec.gitops.fleetRepoUrl}
            platformRepoBasePath: ${schema.spec.gitops.platformRepoBasePath}
            platformRepoPath: ${schema.spec.gitops.platformRepoPath}
            platformRepoRevision: ${schema.spec.gitops.platformRepoRevision}
            platformRepoSecretKey: ${schema.spec.gitops.platformRepoSecretKey}
            platformRepoUrl: ${schema.spec.gitops.platformRepoUrl}
            workloadRepoBasePath: ${schema.spec.gitops.workloadRepoBasePath}
            workloadRepoPath: ${schema.spec.gitops.workloadRepoPath}
            workloadRepoRevision: ${schema.spec.gitops.workloadRepoRevision}
            workloadRepoSecretKey: ${schema.spec.gitops.workloadRepoSecretKey}
            workloadRepoUrl: ${schema.spec.gitops.workloadRepoUrl}

